package com.ksoft.crm.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalSplitPanel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainLayoutDesign extends HorizontalSplitPanel {
    protected VerticalLayout left;
    protected VerticalSplitPanel vsp_left;
    protected VerticalLayout right;
    protected VerticalSplitPanel mid_right_full;
    protected HorizontalLayout top_view;
    protected HorizontalSplitPanel md_right_hsp;
    protected Table customer_details;
    protected VerticalLayout button_view;
    protected Button send_email;
    protected Button send_sms;
    protected Button generate_report;

    public MainLayoutDesign() {
        Design.read(this);
    }
}
