package com.ksoft.crm.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MLDesign extends HorizontalSplitPanel {
    protected Image image_left_top;
    protected Button clear_filters_button;
    protected Label client_type_label;
    protected HorizontalLayout console_label_view;
    protected Label console;
    protected Button info_button;
    protected Button logout_button;
    protected VerticalLayout button_view;
    protected Button send_email;
    protected Button send_sms;
    protected Button generate_report;
    protected Image image_right_bottom;
    protected VerticalLayout middle_vl;
    protected Table table1;
    protected VerticalLayout left_vl;
    protected HorizontalLayout left_hl;
    protected Image image_add_button;
    protected CheckBox check_box_old;
    protected CheckBox check_box_unknown;
    protected CheckBox check_box_new;


    public MLDesign() {
        Design.read(this);
    }
}
